package pojos;
// Generated Dec 16, 2019 2:20:15 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CartHasPackets generated by hbm2java
 */
public class CartHasPackets  implements java.io.Serializable {


     private Integer id;
     private Cart cart;
     private PacketStock packetStock;
     private Integer qty;
     private String status;
     private Date date;
     private Set<InvoiceHasCartHasPackets> invoiceHasCartHasPacketses = new HashSet<InvoiceHasCartHasPackets>(0);

    public CartHasPackets() {
    }

	
    public CartHasPackets(Cart cart, PacketStock packetStock) {
        this.cart = cart;
        this.packetStock = packetStock;
    }
    public CartHasPackets(Cart cart, PacketStock packetStock, Integer qty, String status, Date date, Set<InvoiceHasCartHasPackets> invoiceHasCartHasPacketses) {
       this.cart = cart;
       this.packetStock = packetStock;
       this.qty = qty;
       this.status = status;
       this.date = date;
       this.invoiceHasCartHasPacketses = invoiceHasCartHasPacketses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Cart getCart() {
        return this.cart;
    }
    
    public void setCart(Cart cart) {
        this.cart = cart;
    }
    public PacketStock getPacketStock() {
        return this.packetStock;
    }
    
    public void setPacketStock(PacketStock packetStock) {
        this.packetStock = packetStock;
    }
    public Integer getQty() {
        return this.qty;
    }
    
    public void setQty(Integer qty) {
        this.qty = qty;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Set<InvoiceHasCartHasPackets> getInvoiceHasCartHasPacketses() {
        return this.invoiceHasCartHasPacketses;
    }
    
    public void setInvoiceHasCartHasPacketses(Set<InvoiceHasCartHasPackets> invoiceHasCartHasPacketses) {
        this.invoiceHasCartHasPacketses = invoiceHasCartHasPacketses;
    }




}


