package pojos;
// Generated Dec 16, 2019 2:20:15 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cart generated by hbm2java
 */
public class Cart  implements java.io.Serializable {


     private Integer idcart;
     private User user;
     private Set<CartHasPackages> cartHasPackageses = new HashSet<CartHasPackages>(0);
     private Set<CartHasPackets> cartHasPacketses = new HashSet<CartHasPackets>(0);
     private Set<CartHasItem> cartHasItems = new HashSet<CartHasItem>(0);

    public Cart() {
    }

	
    public Cart(User user) {
        this.user = user;
    }
    public Cart(User user, Set<CartHasPackages> cartHasPackageses, Set<CartHasPackets> cartHasPacketses, Set<CartHasItem> cartHasItems) {
       this.user = user;
       this.cartHasPackageses = cartHasPackageses;
       this.cartHasPacketses = cartHasPacketses;
       this.cartHasItems = cartHasItems;
    }
   
    public Integer getIdcart() {
        return this.idcart;
    }
    
    public void setIdcart(Integer idcart) {
        this.idcart = idcart;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Set<CartHasPackages> getCartHasPackageses() {
        return this.cartHasPackageses;
    }
    
    public void setCartHasPackageses(Set<CartHasPackages> cartHasPackageses) {
        this.cartHasPackageses = cartHasPackageses;
    }
    public Set<CartHasPackets> getCartHasPacketses() {
        return this.cartHasPacketses;
    }
    
    public void setCartHasPacketses(Set<CartHasPackets> cartHasPacketses) {
        this.cartHasPacketses = cartHasPacketses;
    }
    public Set<CartHasItem> getCartHasItems() {
        return this.cartHasItems;
    }
    
    public void setCartHasItems(Set<CartHasItem> cartHasItems) {
        this.cartHasItems = cartHasItems;
    }




}


