package pojos;
// Generated Dec 16, 2019 2:20:15 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CartHasItem generated by hbm2java
 */
public class CartHasItem  implements java.io.Serializable {


     private Integer idCartItem;
     private Cart cart;
     private LooseStock looseStock;
     private Double qty;
     private String status;
     private Date date;
     private Set<InvoiceHasCartItem> invoiceHasCartItems = new HashSet<InvoiceHasCartItem>(0);

    public CartHasItem() {
    }

	
    public CartHasItem(Cart cart, LooseStock looseStock) {
        this.cart = cart;
        this.looseStock = looseStock;
    }
    public CartHasItem(Cart cart, LooseStock looseStock, Double qty, String status, Date date, Set<InvoiceHasCartItem> invoiceHasCartItems) {
       this.cart = cart;
       this.looseStock = looseStock;
       this.qty = qty;
       this.status = status;
       this.date = date;
       this.invoiceHasCartItems = invoiceHasCartItems;
    }
   
    public Integer getIdCartItem() {
        return this.idCartItem;
    }
    
    public void setIdCartItem(Integer idCartItem) {
        this.idCartItem = idCartItem;
    }
    public Cart getCart() {
        return this.cart;
    }
    
    public void setCart(Cart cart) {
        this.cart = cart;
    }
    public LooseStock getLooseStock() {
        return this.looseStock;
    }
    
    public void setLooseStock(LooseStock looseStock) {
        this.looseStock = looseStock;
    }
    public Double getQty() {
        return this.qty;
    }
    
    public void setQty(Double qty) {
        this.qty = qty;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Set<InvoiceHasCartItem> getInvoiceHasCartItems() {
        return this.invoiceHasCartItems;
    }
    
    public void setInvoiceHasCartItems(Set<InvoiceHasCartItem> invoiceHasCartItems) {
        this.invoiceHasCartItems = invoiceHasCartItems;
    }




}


