package pojos;
// Generated Dec 16, 2019 2:20:15 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CartHasPackages generated by hbm2java
 */
public class CartHasPackages  implements java.io.Serializable {


     private int id;
     private Cart cart;
     private Packages packages;
     private Integer qty;
     private String status;
     private Date date;
     private Set<InvoiceHasCartPackages> invoiceHasCartPackageses = new HashSet<InvoiceHasCartPackages>(0);

    public CartHasPackages() {
    }

	
    public CartHasPackages(int id, Cart cart, Packages packages) {
        this.id = id;
        this.cart = cart;
        this.packages = packages;
    }
    public CartHasPackages(int id, Cart cart, Packages packages, Integer qty, String status, Date date, Set<InvoiceHasCartPackages> invoiceHasCartPackageses) {
       this.id = id;
       this.cart = cart;
       this.packages = packages;
       this.qty = qty;
       this.status = status;
       this.date = date;
       this.invoiceHasCartPackageses = invoiceHasCartPackageses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Cart getCart() {
        return this.cart;
    }
    
    public void setCart(Cart cart) {
        this.cart = cart;
    }
    public Packages getPackages() {
        return this.packages;
    }
    
    public void setPackages(Packages packages) {
        this.packages = packages;
    }
    public Integer getQty() {
        return this.qty;
    }
    
    public void setQty(Integer qty) {
        this.qty = qty;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Set<InvoiceHasCartPackages> getInvoiceHasCartPackageses() {
        return this.invoiceHasCartPackageses;
    }
    
    public void setInvoiceHasCartPackageses(Set<InvoiceHasCartPackages> invoiceHasCartPackageses) {
        this.invoiceHasCartPackageses = invoiceHasCartPackageses;
    }




}


