package pojos;
// Generated Dec 16, 2019 2:20:15 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Category generated by hbm2java
 */
public class Category  implements java.io.Serializable {


     private Integer idcategory;
     private String type;
     private String status;
     private Set<Packages> packageses = new HashSet<Packages>(0);

    public Category() {
    }

    public Category(String type, String status, Set<Packages> packageses) {
       this.type = type;
       this.status = status;
       this.packageses = packageses;
    }
   
    public Integer getIdcategory() {
        return this.idcategory;
    }
    
    public void setIdcategory(Integer idcategory) {
        this.idcategory = idcategory;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Set<Packages> getPackageses() {
        return this.packageses;
    }
    
    public void setPackageses(Set<Packages> packageses) {
        this.packageses = packageses;
    }




}


