package pojos;
// Generated Dec 16, 2019 2:20:15 AM by Hibernate Tools 4.3.1



/**
 * Deliverydata generated by hbm2java
 */
public class Deliverydata  implements java.io.Serializable {


     private Integer id;
     private String deliveryType;
     private Double chargePerKm;
     private Double minKm;
     private String deliveryPoint;

    public Deliverydata() {
    }

    public Deliverydata(String deliveryType, Double chargePerKm, Double minKm, String deliveryPoint) {
       this.deliveryType = deliveryType;
       this.chargePerKm = chargePerKm;
       this.minKm = minKm;
       this.deliveryPoint = deliveryPoint;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDeliveryType() {
        return this.deliveryType;
    }
    
    public void setDeliveryType(String deliveryType) {
        this.deliveryType = deliveryType;
    }
    public Double getChargePerKm() {
        return this.chargePerKm;
    }
    
    public void setChargePerKm(Double chargePerKm) {
        this.chargePerKm = chargePerKm;
    }
    public Double getMinKm() {
        return this.minKm;
    }
    
    public void setMinKm(Double minKm) {
        this.minKm = minKm;
    }
    public String getDeliveryPoint() {
        return this.deliveryPoint;
    }
    
    public void setDeliveryPoint(String deliveryPoint) {
        this.deliveryPoint = deliveryPoint;
    }




}


