package pojos;
// Generated Dec 16, 2019 2:20:15 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Interfaces generated by hbm2java
 */
public class Interfaces  implements java.io.Serializable {


     private Integer idinterface;
     private String url;
     private String iterfaceName;
     private Set<Privilage> privilages = new HashSet<Privilage>(0);

    public Interfaces() {
    }

    public Interfaces(String url, String iterfaceName, Set<Privilage> privilages) {
       this.url = url;
       this.iterfaceName = iterfaceName;
       this.privilages = privilages;
    }
   
    public Integer getIdinterface() {
        return this.idinterface;
    }
    
    public void setIdinterface(Integer idinterface) {
        this.idinterface = idinterface;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public String getIterfaceName() {
        return this.iterfaceName;
    }
    
    public void setIterfaceName(String iterfaceName) {
        this.iterfaceName = iterfaceName;
    }
    public Set<Privilage> getPrivilages() {
        return this.privilages;
    }
    
    public void setPrivilages(Set<Privilage> privilages) {
        this.privilages = privilages;
    }




}


