package pojos;
// Generated Dec 16, 2019 2:20:15 AM by Hibernate Tools 4.3.1



/**
 * Invicephoto generated by hbm2java
 */
public class Invicephoto  implements java.io.Serializable {


     private Integer idinvicePhoto;
     private Invoice invoice;
     private User user;
     private String imageUrl;

    public Invicephoto() {
    }

	
    public Invicephoto(Invoice invoice, User user) {
        this.invoice = invoice;
        this.user = user;
    }
    public Invicephoto(Invoice invoice, User user, String imageUrl) {
       this.invoice = invoice;
       this.user = user;
       this.imageUrl = imageUrl;
    }
   
    public Integer getIdinvicePhoto() {
        return this.idinvicePhoto;
    }
    
    public void setIdinvicePhoto(Integer idinvicePhoto) {
        this.idinvicePhoto = idinvicePhoto;
    }
    public Invoice getInvoice() {
        return this.invoice;
    }
    
    public void setInvoice(Invoice invoice) {
        this.invoice = invoice;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getImageUrl() {
        return this.imageUrl;
    }
    
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }




}


