package pojos;
// Generated Dec 16, 2019 2:20:15 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Invoice generated by hbm2java
 */
public class Invoice  implements java.io.Serializable {


     private Integer idinvoice;
     private Location location;
     private User user;
     private Date date;
     private Double netTotal;
     private Double discount;
     private Double subTotal;
     private String status;
     private Set<Invicephoto> invicephotos = new HashSet<Invicephoto>(0);
     private Set<InvoiceHasCartItem> invoiceHasCartItems = new HashSet<InvoiceHasCartItem>(0);
     private Set<InvoiceHasCartPackages> invoiceHasCartPackageses = new HashSet<InvoiceHasCartPackages>(0);
     private Set<InvoiceHasCartHasPackets> invoiceHasCartHasPacketses = new HashSet<InvoiceHasCartHasPackets>(0);

    public Invoice() {
    }

	
    public Invoice(Location location, User user) {
        this.location = location;
        this.user = user;
    }
    public Invoice(Location location, User user, Date date, Double netTotal, Double discount, Double subTotal, String status, Set<Invicephoto> invicephotos, Set<InvoiceHasCartItem> invoiceHasCartItems, Set<InvoiceHasCartPackages> invoiceHasCartPackageses, Set<InvoiceHasCartHasPackets> invoiceHasCartHasPacketses) {
       this.location = location;
       this.user = user;
       this.date = date;
       this.netTotal = netTotal;
       this.discount = discount;
       this.subTotal = subTotal;
       this.status = status;
       this.invicephotos = invicephotos;
       this.invoiceHasCartItems = invoiceHasCartItems;
       this.invoiceHasCartPackageses = invoiceHasCartPackageses;
       this.invoiceHasCartHasPacketses = invoiceHasCartHasPacketses;
    }
   
    public Integer getIdinvoice() {
        return this.idinvoice;
    }
    
    public void setIdinvoice(Integer idinvoice) {
        this.idinvoice = idinvoice;
    }
    public Location getLocation() {
        return this.location;
    }
    
    public void setLocation(Location location) {
        this.location = location;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Double getNetTotal() {
        return this.netTotal;
    }
    
    public void setNetTotal(Double netTotal) {
        this.netTotal = netTotal;
    }
    public Double getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(Double discount) {
        this.discount = discount;
    }
    public Double getSubTotal() {
        return this.subTotal;
    }
    
    public void setSubTotal(Double subTotal) {
        this.subTotal = subTotal;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Set<Invicephoto> getInvicephotos() {
        return this.invicephotos;
    }
    
    public void setInvicephotos(Set<Invicephoto> invicephotos) {
        this.invicephotos = invicephotos;
    }
    public Set<InvoiceHasCartItem> getInvoiceHasCartItems() {
        return this.invoiceHasCartItems;
    }
    
    public void setInvoiceHasCartItems(Set<InvoiceHasCartItem> invoiceHasCartItems) {
        this.invoiceHasCartItems = invoiceHasCartItems;
    }
    public Set<InvoiceHasCartPackages> getInvoiceHasCartPackageses() {
        return this.invoiceHasCartPackageses;
    }
    
    public void setInvoiceHasCartPackageses(Set<InvoiceHasCartPackages> invoiceHasCartPackageses) {
        this.invoiceHasCartPackageses = invoiceHasCartPackageses;
    }
    public Set<InvoiceHasCartHasPackets> getInvoiceHasCartHasPacketses() {
        return this.invoiceHasCartHasPacketses;
    }
    
    public void setInvoiceHasCartHasPacketses(Set<InvoiceHasCartHasPackets> invoiceHasCartHasPacketses) {
        this.invoiceHasCartHasPacketses = invoiceHasCartHasPacketses;
    }




}


