package pojos;
// Generated Dec 16, 2019 2:20:15 AM by Hibernate Tools 4.3.1



/**
 * InvoiceHasCartItem generated by hbm2java
 */
public class InvoiceHasCartItem  implements java.io.Serializable {


     private Integer id;
     private CartHasItem cartHasItem;
     private Invoice invoice;
     private Double qty;
     private Double price;

    public InvoiceHasCartItem() {
    }

	
    public InvoiceHasCartItem(CartHasItem cartHasItem, Invoice invoice) {
        this.cartHasItem = cartHasItem;
        this.invoice = invoice;
    }
    public InvoiceHasCartItem(CartHasItem cartHasItem, Invoice invoice, Double qty, Double price) {
       this.cartHasItem = cartHasItem;
       this.invoice = invoice;
       this.qty = qty;
       this.price = price;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public CartHasItem getCartHasItem() {
        return this.cartHasItem;
    }
    
    public void setCartHasItem(CartHasItem cartHasItem) {
        this.cartHasItem = cartHasItem;
    }
    public Invoice getInvoice() {
        return this.invoice;
    }
    
    public void setInvoice(Invoice invoice) {
        this.invoice = invoice;
    }
    public Double getQty() {
        return this.qty;
    }
    
    public void setQty(Double qty) {
        this.qty = qty;
    }
    public Double getPrice() {
        return this.price;
    }
    
    public void setPrice(Double price) {
        this.price = price;
    }




}


