package pojos;
// Generated Dec 16, 2019 2:20:15 AM by Hibernate Tools 4.3.1



/**
 * InvoiceHasCartHasPackets generated by hbm2java
 */
public class InvoiceHasCartHasPackets  implements java.io.Serializable {


     private Integer id;
     private CartHasPackets cartHasPackets;
     private Invoice invoice;
     private Integer qty;
     private Double price;

    public InvoiceHasCartHasPackets() {
    }

	
    public InvoiceHasCartHasPackets(CartHasPackets cartHasPackets, Invoice invoice) {
        this.cartHasPackets = cartHasPackets;
        this.invoice = invoice;
    }
    public InvoiceHasCartHasPackets(CartHasPackets cartHasPackets, Invoice invoice, Integer qty, Double price) {
       this.cartHasPackets = cartHasPackets;
       this.invoice = invoice;
       this.qty = qty;
       this.price = price;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public CartHasPackets getCartHasPackets() {
        return this.cartHasPackets;
    }
    
    public void setCartHasPackets(CartHasPackets cartHasPackets) {
        this.cartHasPackets = cartHasPackets;
    }
    public Invoice getInvoice() {
        return this.invoice;
    }
    
    public void setInvoice(Invoice invoice) {
        this.invoice = invoice;
    }
    public Integer getQty() {
        return this.qty;
    }
    
    public void setQty(Integer qty) {
        this.qty = qty;
    }
    public Double getPrice() {
        return this.price;
    }
    
    public void setPrice(Double price) {
        this.price = price;
    }




}


