package pojos;
// Generated Dec 16, 2019 2:20:15 AM by Hibernate Tools 4.3.1



/**
 * InvoiceHasCartPackages generated by hbm2java
 */
public class InvoiceHasCartPackages  implements java.io.Serializable {


     private Integer id;
     private CartHasPackages cartHasPackages;
     private Invoice invoice;
     private Integer qty;
     private Double price;

    public InvoiceHasCartPackages() {
    }

	
    public InvoiceHasCartPackages(CartHasPackages cartHasPackages, Invoice invoice) {
        this.cartHasPackages = cartHasPackages;
        this.invoice = invoice;
    }
    public InvoiceHasCartPackages(CartHasPackages cartHasPackages, Invoice invoice, Integer qty, Double price) {
       this.cartHasPackages = cartHasPackages;
       this.invoice = invoice;
       this.qty = qty;
       this.price = price;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public CartHasPackages getCartHasPackages() {
        return this.cartHasPackages;
    }
    
    public void setCartHasPackages(CartHasPackages cartHasPackages) {
        this.cartHasPackages = cartHasPackages;
    }
    public Invoice getInvoice() {
        return this.invoice;
    }
    
    public void setInvoice(Invoice invoice) {
        this.invoice = invoice;
    }
    public Integer getQty() {
        return this.qty;
    }
    
    public void setQty(Integer qty) {
        this.qty = qty;
    }
    public Double getPrice() {
        return this.price;
    }
    
    public void setPrice(Double price) {
        this.price = price;
    }




}


