package pojos;
// Generated Dec 16, 2019 2:20:15 AM by Hibernate Tools 4.3.1



/**
 * Limit generated by hbm2java
 */
public class Limit  implements java.io.Serializable {


     private Integer idlimit;
     private Usertype usertype;
     private Double totalQty;
     private Double totalPrice;

    public Limit() {
    }

	
    public Limit(Usertype usertype) {
        this.usertype = usertype;
    }
    public Limit(Usertype usertype, Double totalQty, Double totalPrice) {
       this.usertype = usertype;
       this.totalQty = totalQty;
       this.totalPrice = totalPrice;
    }
   
    public Integer getIdlimit() {
        return this.idlimit;
    }
    
    public void setIdlimit(Integer idlimit) {
        this.idlimit = idlimit;
    }
    public Usertype getUsertype() {
        return this.usertype;
    }
    
    public void setUsertype(Usertype usertype) {
        this.usertype = usertype;
    }
    public Double getTotalQty() {
        return this.totalQty;
    }
    
    public void setTotalQty(Double totalQty) {
        this.totalQty = totalQty;
    }
    public Double getTotalPrice() {
        return this.totalPrice;
    }
    
    public void setTotalPrice(Double totalPrice) {
        this.totalPrice = totalPrice;
    }




}


