package pojos;
// Generated Dec 16, 2019 2:20:15 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Location generated by hbm2java
 */
public class Location  implements java.io.Serializable {


     private Integer idlocation;
     private User user;
     private Zip zip;
     private String street;
     private String address;
     private Double lang;
     private Double lat;
     private Integer tel;
     private Set<Invoice> invoices = new HashSet<Invoice>(0);

    public Location() {
    }

	
    public Location(User user, Zip zip) {
        this.user = user;
        this.zip = zip;
    }
    public Location(User user, Zip zip, String street, String address, Double lang, Double lat, Integer tel, Set<Invoice> invoices) {
       this.user = user;
       this.zip = zip;
       this.street = street;
       this.address = address;
       this.lang = lang;
       this.lat = lat;
       this.tel = tel;
       this.invoices = invoices;
    }
   
    public Integer getIdlocation() {
        return this.idlocation;
    }
    
    public void setIdlocation(Integer idlocation) {
        this.idlocation = idlocation;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Zip getZip() {
        return this.zip;
    }
    
    public void setZip(Zip zip) {
        this.zip = zip;
    }
    public String getStreet() {
        return this.street;
    }
    
    public void setStreet(String street) {
        this.street = street;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public Double getLang() {
        return this.lang;
    }
    
    public void setLang(Double lang) {
        this.lang = lang;
    }
    public Double getLat() {
        return this.lat;
    }
    
    public void setLat(Double lat) {
        this.lat = lat;
    }
    public Integer getTel() {
        return this.tel;
    }
    
    public void setTel(Integer tel) {
        this.tel = tel;
    }
    public Set<Invoice> getInvoices() {
        return this.invoices;
    }
    
    public void setInvoices(Set<Invoice> invoices) {
        this.invoices = invoices;
    }




}


