package pojos;
// Generated Dec 16, 2019 2:20:15 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * LooseStock generated by hbm2java
 */
public class LooseStock  implements java.io.Serializable {


     private Integer iditem;
     private Product product;
     private Double qty;
     private String status;
     private double uprice;
     private Set<CartHasItem> cartHasItems = new HashSet<CartHasItem>(0);

    public LooseStock() {
    }

	
    public LooseStock(Product product, double uprice) {
        this.product = product;
        this.uprice = uprice;
    }
    public LooseStock(Product product, Double qty, String status, double uprice, Set<CartHasItem> cartHasItems) {
       this.product = product;
       this.qty = qty;
       this.status = status;
       this.uprice = uprice;
       this.cartHasItems = cartHasItems;
    }
   
    public Integer getIditem() {
        return this.iditem;
    }
    
    public void setIditem(Integer iditem) {
        this.iditem = iditem;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public Double getQty() {
        return this.qty;
    }
    
    public void setQty(Double qty) {
        this.qty = qty;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public double getUprice() {
        return this.uprice;
    }
    
    public void setUprice(double uprice) {
        this.uprice = uprice;
    }
    public Set<CartHasItem> getCartHasItems() {
        return this.cartHasItems;
    }
    
    public void setCartHasItems(Set<CartHasItem> cartHasItems) {
        this.cartHasItems = cartHasItems;
    }




}


