package pojos;
// Generated Dec 16, 2019 2:20:15 AM by Hibernate Tools 4.3.1



/**
 * PackageReview generated by hbm2java
 */
public class PackageReview  implements java.io.Serializable {


     private int idpackageReview;
     private Packages packages;
     private User user;
     private Integer rate;
     private String description;

    public PackageReview() {
    }

	
    public PackageReview(int idpackageReview, Packages packages, User user) {
        this.idpackageReview = idpackageReview;
        this.packages = packages;
        this.user = user;
    }
    public PackageReview(int idpackageReview, Packages packages, User user, Integer rate, String description) {
       this.idpackageReview = idpackageReview;
       this.packages = packages;
       this.user = user;
       this.rate = rate;
       this.description = description;
    }
   
    public int getIdpackageReview() {
        return this.idpackageReview;
    }
    
    public void setIdpackageReview(int idpackageReview) {
        this.idpackageReview = idpackageReview;
    }
    public Packages getPackages() {
        return this.packages;
    }
    
    public void setPackages(Packages packages) {
        this.packages = packages;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Integer getRate() {
        return this.rate;
    }
    
    public void setRate(Integer rate) {
        this.rate = rate;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


