package pojos;
// Generated Dec 16, 2019 2:20:15 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PacketStock generated by hbm2java
 */
public class PacketStock  implements java.io.Serializable {


     private Integer id;
     private Packet packet;
     private Integer qty;
     private Date exp;
     private Date man;
     private Double price;
     private String status;
     private Set<CartHasPackets> cartHasPacketses = new HashSet<CartHasPackets>(0);

    public PacketStock() {
    }

	
    public PacketStock(Packet packet) {
        this.packet = packet;
    }
    public PacketStock(Packet packet, Integer qty, Date exp, Date man, Double price, String status, Set<CartHasPackets> cartHasPacketses) {
       this.packet = packet;
       this.qty = qty;
       this.exp = exp;
       this.man = man;
       this.price = price;
       this.status = status;
       this.cartHasPacketses = cartHasPacketses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Packet getPacket() {
        return this.packet;
    }
    
    public void setPacket(Packet packet) {
        this.packet = packet;
    }
    public Integer getQty() {
        return this.qty;
    }
    
    public void setQty(Integer qty) {
        this.qty = qty;
    }
    public Date getExp() {
        return this.exp;
    }
    
    public void setExp(Date exp) {
        this.exp = exp;
    }
    public Date getMan() {
        return this.man;
    }
    
    public void setMan(Date man) {
        this.man = man;
    }
    public Double getPrice() {
        return this.price;
    }
    
    public void setPrice(Double price) {
        this.price = price;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Set<CartHasPackets> getCartHasPacketses() {
        return this.cartHasPacketses;
    }
    
    public void setCartHasPacketses(Set<CartHasPackets> cartHasPacketses) {
        this.cartHasPacketses = cartHasPacketses;
    }




}


