package pojos;
// Generated Dec 16, 2019 2:20:15 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Packet generated by hbm2java
 */
public class Packet  implements java.io.Serializable {


     private Integer idpacket;
     private String name;
     private Double weight;
     private String status;
     private String img;
     private String type;
     private Set<PacketStock> packetStocks = new HashSet<PacketStock>(0);

    public Packet() {
    }

    public Packet(String name, Double weight, String status, String img, String type, Set<PacketStock> packetStocks) {
       this.name = name;
       this.weight = weight;
       this.status = status;
       this.img = img;
       this.type = type;
       this.packetStocks = packetStocks;
    }
   
    public Integer getIdpacket() {
        return this.idpacket;
    }
    
    public void setIdpacket(Integer idpacket) {
        this.idpacket = idpacket;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Double getWeight() {
        return this.weight;
    }
    
    public void setWeight(Double weight) {
        this.weight = weight;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getImg() {
        return this.img;
    }
    
    public void setImg(String img) {
        this.img = img;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public Set<PacketStock> getPacketStocks() {
        return this.packetStocks;
    }
    
    public void setPacketStocks(Set<PacketStock> packetStocks) {
        this.packetStocks = packetStocks;
    }




}


