package pojos;
// Generated Dec 16, 2019 2:20:15 AM by Hibernate Tools 4.3.1



/**
 * Privilage generated by hbm2java
 */
public class Privilage  implements java.io.Serializable {


     private int idprivilage;
     private Interfaces interfaces;
     private Usertype usertype;

    public Privilage() {
    }

    public Privilage(int idprivilage, Interfaces interfaces, Usertype usertype) {
       this.idprivilage = idprivilage;
       this.interfaces = interfaces;
       this.usertype = usertype;
    }
   
    public int getIdprivilage() {
        return this.idprivilage;
    }
    
    public void setIdprivilage(int idprivilage) {
        this.idprivilage = idprivilage;
    }
    public Interfaces getInterfaces() {
        return this.interfaces;
    }
    
    public void setInterfaces(Interfaces interfaces) {
        this.interfaces = interfaces;
    }
    public Usertype getUsertype() {
        return this.usertype;
    }
    
    public void setUsertype(Usertype usertype) {
        this.usertype = usertype;
    }




}


