package pojos;
// Generated Dec 16, 2019 2:20:15 AM by Hibernate Tools 4.3.1



/**
 * Resetcode generated by hbm2java
 */
public class Resetcode  implements java.io.Serializable {


     private Integer idresetCode;
     private User user;
     private String code;

    public Resetcode() {
    }

	
    public Resetcode(User user) {
        this.user = user;
    }
    public Resetcode(User user, String code) {
       this.user = user;
       this.code = code;
    }
   
    public Integer getIdresetCode() {
        return this.idresetCode;
    }
    
    public void setIdresetCode(Integer idresetCode) {
        this.idresetCode = idresetCode;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }




}


