package pojos;
// Generated Dec 16, 2019 2:20:15 AM by Hibernate Tools 4.3.1



/**
 * SessionActivities generated by hbm2java
 */
public class SessionActivities  implements java.io.Serializable {


     private int idsessionActivities;
     private LoginSession loginSession;
     private String description;
     private String sessionActivitiescol;

    public SessionActivities() {
    }

	
    public SessionActivities(int idsessionActivities, LoginSession loginSession) {
        this.idsessionActivities = idsessionActivities;
        this.loginSession = loginSession;
    }
    public SessionActivities(int idsessionActivities, LoginSession loginSession, String description, String sessionActivitiescol) {
       this.idsessionActivities = idsessionActivities;
       this.loginSession = loginSession;
       this.description = description;
       this.sessionActivitiescol = sessionActivitiescol;
    }
   
    public int getIdsessionActivities() {
        return this.idsessionActivities;
    }
    
    public void setIdsessionActivities(int idsessionActivities) {
        this.idsessionActivities = idsessionActivities;
    }
    public LoginSession getLoginSession() {
        return this.loginSession;
    }
    
    public void setLoginSession(LoginSession loginSession) {
        this.loginSession = loginSession;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getSessionActivitiescol() {
        return this.sessionActivitiescol;
    }
    
    public void setSessionActivitiescol(String sessionActivitiescol) {
        this.sessionActivitiescol = sessionActivitiescol;
    }




}


