package pojos;
// Generated Dec 16, 2019 2:20:15 AM by Hibernate Tools 4.3.1



/**
 * Supplier generated by hbm2java
 */
public class Supplier  implements java.io.Serializable {


     private int idsupplier;
     private Product product;
     private String name;
     private String address;
     private String email;
     private String tel;

    public Supplier() {
    }

	
    public Supplier(int idsupplier, Product product) {
        this.idsupplier = idsupplier;
        this.product = product;
    }
    public Supplier(int idsupplier, Product product, String name, String address, String email, String tel) {
       this.idsupplier = idsupplier;
       this.product = product;
       this.name = name;
       this.address = address;
       this.email = email;
       this.tel = tel;
    }
   
    public int getIdsupplier() {
        return this.idsupplier;
    }
    
    public void setIdsupplier(int idsupplier) {
        this.idsupplier = idsupplier;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getTel() {
        return this.tel;
    }
    
    public void setTel(String tel) {
        this.tel = tel;
    }




}


