package pojos;
// Generated Dec 16, 2019 2:20:15 AM by Hibernate Tools 4.3.1



/**
 * UsertypeDiscount generated by hbm2java
 */
public class UsertypeDiscount  implements java.io.Serializable {


     private int id;
     private Usertype usertype;
     private Double percentage;

    public UsertypeDiscount() {
    }

	
    public UsertypeDiscount(int id, Usertype usertype) {
        this.id = id;
        this.usertype = usertype;
    }
    public UsertypeDiscount(int id, Usertype usertype, Double percentage) {
       this.id = id;
       this.usertype = usertype;
       this.percentage = percentage;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Usertype getUsertype() {
        return this.usertype;
    }
    
    public void setUsertype(Usertype usertype) {
        this.usertype = usertype;
    }
    public Double getPercentage() {
        return this.percentage;
    }
    
    public void setPercentage(Double percentage) {
        this.percentage = percentage;
    }




}


