package pojos;
// Generated Dec 16, 2019 2:20:15 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * UserLogin generated by hbm2java
 */
public class UserLogin  implements java.io.Serializable {


     private int iduserLogin;
     private User user;
     private String username;
     private String password;
     private Set<LoginSession> loginSessions = new HashSet<LoginSession>(0);

    public UserLogin() {
    }

	
    public UserLogin(int iduserLogin, User user) {
        this.iduserLogin = iduserLogin;
        this.user = user;
    }
    public UserLogin(int iduserLogin, User user, String username, String password, Set<LoginSession> loginSessions) {
       this.iduserLogin = iduserLogin;
       this.user = user;
       this.username = username;
       this.password = password;
       this.loginSessions = loginSessions;
    }
   
    public int getIduserLogin() {
        return this.iduserLogin;
    }
    
    public void setIduserLogin(int iduserLogin) {
        this.iduserLogin = iduserLogin;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Set<LoginSession> getLoginSessions() {
        return this.loginSessions;
    }
    
    public void setLoginSessions(Set<LoginSession> loginSessions) {
        this.loginSessions = loginSessions;
    }




}


