package pojos;
// Generated Dec 16, 2019 2:20:15 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usertype generated by hbm2java
 */
public class Usertype  implements java.io.Serializable {


     private Integer idusertype;
     private String userType;
     private Set<Privilage> privilages = new HashSet<Privilage>(0);
     private Set<User> users = new HashSet<User>(0);
     private Set<Limit> limits = new HashSet<Limit>(0);
     private Set<UsertypeDiscount> usertypeDiscounts = new HashSet<UsertypeDiscount>(0);

    public Usertype() {
    }

    public Usertype(String userType, Set<Privilage> privilages, Set<User> users, Set<Limit> limits, Set<UsertypeDiscount> usertypeDiscounts) {
       this.userType = userType;
       this.privilages = privilages;
       this.users = users;
       this.limits = limits;
       this.usertypeDiscounts = usertypeDiscounts;
    }
   
    public Integer getIdusertype() {
        return this.idusertype;
    }
    
    public void setIdusertype(Integer idusertype) {
        this.idusertype = idusertype;
    }
    public String getUserType() {
        return this.userType;
    }
    
    public void setUserType(String userType) {
        this.userType = userType;
    }
    public Set<Privilage> getPrivilages() {
        return this.privilages;
    }
    
    public void setPrivilages(Set<Privilage> privilages) {
        this.privilages = privilages;
    }
    public Set<User> getUsers() {
        return this.users;
    }
    
    public void setUsers(Set<User> users) {
        this.users = users;
    }
    public Set<Limit> getLimits() {
        return this.limits;
    }
    
    public void setLimits(Set<Limit> limits) {
        this.limits = limits;
    }
    public Set<UsertypeDiscount> getUsertypeDiscounts() {
        return this.usertypeDiscounts;
    }
    
    public void setUsertypeDiscounts(Set<UsertypeDiscount> usertypeDiscounts) {
        this.usertypeDiscounts = usertypeDiscounts;
    }




}


