package pojos;
// Generated Dec 16, 2019 2:20:15 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer iduser;
     private Usertype usertype;
     private String name;
     private String email;
     private String password;
     private Date date;
     private Boolean status;
     private String ooStatus;
     private Set<Cart> carts = new HashSet<Cart>(0);
     private Set<PackageReview> packageReviews = new HashSet<PackageReview>(0);
     private Set<DiscountCodes> discountCodeses = new HashSet<DiscountCodes>(0);
     private Set<Resetcode> resetcodes = new HashSet<Resetcode>(0);
     private Set<Invicephoto> invicephotos = new HashSet<Invicephoto>(0);
     private Set<UserLogin> userLogins = new HashSet<UserLogin>(0);
     private Set<Vehicle> vehicles = new HashSet<Vehicle>(0);
     private Set<Invoice> invoices = new HashSet<Invoice>(0);
     private Set<Location> locations = new HashSet<Location>(0);

    public User() {
    }

	
    public User(Usertype usertype) {
        this.usertype = usertype;
    }
    public User(Usertype usertype, String name, String email, String password, Date date, Boolean status, String ooStatus, Set<Cart> carts, Set<PackageReview> packageReviews, Set<DiscountCodes> discountCodeses, Set<Resetcode> resetcodes, Set<Invicephoto> invicephotos, Set<UserLogin> userLogins, Set<Vehicle> vehicles, Set<Invoice> invoices, Set<Location> locations) {
       this.usertype = usertype;
       this.name = name;
       this.email = email;
       this.password = password;
       this.date = date;
       this.status = status;
       this.ooStatus = ooStatus;
       this.carts = carts;
       this.packageReviews = packageReviews;
       this.discountCodeses = discountCodeses;
       this.resetcodes = resetcodes;
       this.invicephotos = invicephotos;
       this.userLogins = userLogins;
       this.vehicles = vehicles;
       this.invoices = invoices;
       this.locations = locations;
    }
   
    public Integer getIduser() {
        return this.iduser;
    }
    
    public void setIduser(Integer iduser) {
        this.iduser = iduser;
    }
    public Usertype getUsertype() {
        return this.usertype;
    }
    
    public void setUsertype(Usertype usertype) {
        this.usertype = usertype;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Boolean getStatus() {
        return this.status;
    }
    
    public void setStatus(Boolean status) {
        this.status = status;
    }
    public String getOoStatus() {
        return this.ooStatus;
    }
    
    public void setOoStatus(String ooStatus) {
        this.ooStatus = ooStatus;
    }
    public Set<Cart> getCarts() {
        return this.carts;
    }
    
    public void setCarts(Set<Cart> carts) {
        this.carts = carts;
    }
    public Set<PackageReview> getPackageReviews() {
        return this.packageReviews;
    }
    
    public void setPackageReviews(Set<PackageReview> packageReviews) {
        this.packageReviews = packageReviews;
    }
    public Set<DiscountCodes> getDiscountCodeses() {
        return this.discountCodeses;
    }
    
    public void setDiscountCodeses(Set<DiscountCodes> discountCodeses) {
        this.discountCodeses = discountCodeses;
    }
    public Set<Resetcode> getResetcodes() {
        return this.resetcodes;
    }
    
    public void setResetcodes(Set<Resetcode> resetcodes) {
        this.resetcodes = resetcodes;
    }
    public Set<Invicephoto> getInvicephotos() {
        return this.invicephotos;
    }
    
    public void setInvicephotos(Set<Invicephoto> invicephotos) {
        this.invicephotos = invicephotos;
    }
    public Set<UserLogin> getUserLogins() {
        return this.userLogins;
    }
    
    public void setUserLogins(Set<UserLogin> userLogins) {
        this.userLogins = userLogins;
    }
    public Set<Vehicle> getVehicles() {
        return this.vehicles;
    }
    
    public void setVehicles(Set<Vehicle> vehicles) {
        this.vehicles = vehicles;
    }
    public Set<Invoice> getInvoices() {
        return this.invoices;
    }
    
    public void setInvoices(Set<Invoice> invoices) {
        this.invoices = invoices;
    }
    public Set<Location> getLocations() {
        return this.locations;
    }
    
    public void setLocations(Set<Location> locations) {
        this.locations = locations;
    }




}


