package pojos;
// Generated Dec 16, 2019 2:20:15 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Vehicletype generated by hbm2java
 */
public class Vehicletype  implements java.io.Serializable {


     private int idvehicleType;
     private String type;
     private Set<Vehicle> vehicles = new HashSet<Vehicle>(0);

    public Vehicletype() {
    }

	
    public Vehicletype(int idvehicleType) {
        this.idvehicleType = idvehicleType;
    }
    public Vehicletype(int idvehicleType, String type, Set<Vehicle> vehicles) {
       this.idvehicleType = idvehicleType;
       this.type = type;
       this.vehicles = vehicles;
    }
   
    public int getIdvehicleType() {
        return this.idvehicleType;
    }
    
    public void setIdvehicleType(int idvehicleType) {
        this.idvehicleType = idvehicleType;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public Set<Vehicle> getVehicles() {
        return this.vehicles;
    }
    
    public void setVehicles(Set<Vehicle> vehicles) {
        this.vehicles = vehicles;
    }




}


