package pojos;
// Generated Dec 16, 2019 2:20:15 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Zip generated by hbm2java
 */
public class Zip  implements java.io.Serializable {


     private Integer idzip;
     private String zipcode;
     private Double charge;
     private Set<Location> locations = new HashSet<Location>(0);

    public Zip() {
    }

    public Zip(String zipcode, Double charge, Set<Location> locations) {
       this.zipcode = zipcode;
       this.charge = charge;
       this.locations = locations;
    }
   
    public Integer getIdzip() {
        return this.idzip;
    }
    
    public void setIdzip(Integer idzip) {
        this.idzip = idzip;
    }
    public String getZipcode() {
        return this.zipcode;
    }
    
    public void setZipcode(String zipcode) {
        this.zipcode = zipcode;
    }
    public Double getCharge() {
        return this.charge;
    }
    
    public void setCharge(Double charge) {
        this.charge = charge;
    }
    public Set<Location> getLocations() {
        return this.locations;
    }
    
    public void setLocations(Set<Location> locations) {
        this.locations = locations;
    }




}


